# Generated by Django 5.2.1 on 2025-07-09 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('chat', models.JSONField()),
                ('quote_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chat Conversation',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'faq',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceConversations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=20)),
                ('audio_file', models.URLField(blank=True, help_text='URL to call recording')),
                ('chat', models.JSONField()),
                ('quote_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Voice Conversation',
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='Chat', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=20)),
                ('post_code', models.CharField(max_length=20)),
                ('product_id', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('decoration_requested', models.BooleanField(default=False)),
                ('decoration_mode', models.CharField(blank=True, max_length=255, null=True)),
                ('decoration_mode_id', models.PositiveIntegerField(blank=True, null=True)),
                ('color_szie', models.CharField(blank=True, max_length=100, null=True)),
                ('color_size_id', models.PositiveIntegerField(blank=True, null=True)),
                ('delivery_time', models.CharField(blank=True, max_length=255, null=True)),
                ('quote_status', models.CharField(default='pending', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to='FastPromos.chatconversations')),
            ],
            options={
                'verbose_name': 'Quote Request',
            },
        ),
    ]
