# Generated by Django 5.2.1 on 2025-07-09 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FastPromos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoterequest',
            old_name='color_szie',
            new_name='color_size',
        ),
    ]
