# Generated by Django 5.2.1 on 2025-07-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FastPromos', '0002_rename_color_szie_quoterequest_color_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='product_name',
            field=models.CharField(max_length=255, verbose_name='Product Name'),
        ),
    ]
