# Generated by Django 5.2.1 on 2025-07-10 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FastPromos', '0003_alter_quoterequest_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='voiceflow_knowledgebase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=255)),
                ('document_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='chatconversations',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='chatconversations',
            name='quote_requested',
            field=models.BooleanField(default=False, verbose_name='Quote Requested'),
        ),
        migrations.AlterField(
            model_name='chatconversations',
            name='user_id',
            field=models.CharField(max_length=255, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to='FastPromos.chatconversations', verbose_name='Chat ID'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='color_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Color/Size'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='color_size_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Color/Size ID'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='decoration_mode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Decoration Mode'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='decoration_mode_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Decoration Mode ID'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='decoration_requested',
            field=models.BooleanField(default=False, verbose_name='Decoration Requested'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Delivery Time'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='phone_no',
            field=models.CharField(max_length=20, verbose_name='Phone No.'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='post_code',
            field=models.CharField(max_length=20, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='product_id',
            field=models.CharField(max_length=255, verbose_name='Product ID'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='quote_status',
            field=models.CharField(default='pending', max_length=100, verbose_name='Quote Status'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='voiceconversations',
            name='audio_file',
            field=models.URLField(blank=True, help_text='URL to call recording', verbose_name='Audio File'),
        ),
        migrations.AlterField(
            model_name='voiceconversations',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='voiceconversations',
            name='quote_requested',
            field=models.BooleanField(default=False, verbose_name='Quote Requested'),
        ),
        migrations.AlterField(
            model_name='voiceconversations',
            name='user_id',
            field=models.CharField(max_length=255, verbose_name='User ID'),
        ),
    ]
