# Generated by Django 5.2.1 on 2025-07-10 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FastPromos', '0004_voiceflow_knowledgebase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceflow_knowledgebase',
            name='row_count',
            field=models.CharField(default=datetime.datetime(2025, 7, 10, 6, 51, 16, 802213, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
