# Generated by Django 5.2.1 on 2025-07-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FastPromos', '0005_voiceflow_knowledgebase_row_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='color_size_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Color/Size ID'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='decoration_mode_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Decoration Mode ID'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='quantity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Quantity'),
        ),
    ]
