# Generated by Django 5.2.1 on 2025-07-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FastPromos', '0006_alter_quoterequest_color_size_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='logo_colors',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Logo Colors'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='total_logos',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Total Logos'),
        ),
    ]
