# Generated by Django 5.2.1 on 2025-07-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FastPromos', '0007_quoterequest_logo_colors_quoterequest_total_logos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='color_size',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='color_size_id',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='logo_colors',
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='colour_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Colour/Size'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='colour_size_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Colour/Size ID'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='logo_colours',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Logo Colours'),
        ),
    ]
