# Generated by Django 5.2.1 on 2025-07-14 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FastPromos', '0008_remove_quoterequest_color_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Delivery'),
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(max_length=50, unique=True, verbose_name='Quotation Number')),
                ('quantity', models.CharField(max_length=50, unique=True, verbose_name='Quantity')),
                ('branding_applied', models.CharField(max_length=50, unique=True, verbose_name='Branding Applied')),
                ('base_unit_price', models.CharField(max_length=50, unique=True, verbose_name='Base Unit Price')),
                ('decoration_unit_price', models.CharField(max_length=50, unique=True, verbose_name='Decoration Unit Price')),
                ('no_placement', models.CharField(max_length=50, unique=True, verbose_name='Total Placement')),
                ('setup_fee', models.CharField(max_length=50, unique=True, verbose_name='Decoration Setup Fee')),
                ('total_decoration_cost', models.CharField(max_length=50, unique=True, verbose_name='Total Decoration Cost')),
                ('total_setup_cost', models.CharField(max_length=50, unique=True, verbose_name='Total Setup Cost')),
                ('decoration_total', models.CharField(max_length=50, unique=True, verbose_name='Decoration/Setup Total')),
                ('all_in_unit_cost', models.CharField(max_length=50, unique=True, verbose_name='All In Unit Cost')),
                ('final_unit_cost', models.CharField(max_length=50, unique=True, verbose_name='Final Unit Cost')),
                ('total_cost', models.CharField(max_length=50, unique=True, verbose_name='Total Cost')),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='FastPromos.quoterequest', verbose_name='Related Quote Request')),
            ],
        ),
    ]
