# Generated by Django 5.2.1 on 2025-07-14 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FastPromos', '0009_alter_quoterequest_delivery_time_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 14, 6, 49, 3, 661889, tzinfo=datetime.timezone.utc), verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='quote_status',
            field=models.CharField(default='pending', max_length=100, verbose_name='Quote Status'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
