# Generated by Django 5.2.1 on 2025-07-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FastPromos', '0010_quotation_created_at_quotation_quote_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='all_in_unit_cost',
            field=models.CharField(max_length=255, verbose_name='All In Unit Cost'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='base_unit_price',
            field=models.CharField(max_length=255, verbose_name='Base Unit Price'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='branding_applied',
            field=models.CharField(max_length=255, verbose_name='Branding Applied'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='decoration_total',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Decoration/Setup Total'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='decoration_unit_price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Decoration Unit Price'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='final_unit_cost',
            field=models.CharField(max_length=255, verbose_name='Final Unit Cost'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='no_placement',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Total Placement'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quantity',
            field=models.CharField(max_length=255, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='setup_fee',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Decoration Setup Fee'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='total_cost',
            field=models.CharField(max_length=255, verbose_name='Total Cost'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='total_decoration_cost',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Total Decoration Cost'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='total_setup_cost',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Total Setup Cost'),
        ),
    ]
