# Generated by Django 5.2.1 on 2025-07-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FastPromos', '0011_alter_quotation_all_in_unit_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='branding_applied',
        ),
        migrations.AddField(
            model_name='quotation',
            name='decoration_requested',
            field=models.BooleanField(default=False, verbose_name='Decoration Requested'),
        ),
    ]
