# Generated by Django 5.2.1 on 2025-07-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FastPromos', '0012_remove_quotation_branding_applied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversations',
            name='platform',
            field=models.CharField(default='web-chat', max_length=255, verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quote_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Quote Number'),
        ),
    ]
