# Generated by Django 5.2.1 on 2025-07-05 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retells', '0022_lead_call_retry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callhistory',
            options={'verbose_name': 'Call History', 'verbose_name_plural': 'Call History'},
        ),
    ]
